version: '3.9'
services:
  app:
    image: app
    build:
      context: ./.devcontainer
      args:
        - VARIANT=16-bullseye
    user: node
    volumes:
      - workspace:/workspace:rw
    ports:
      - 8080:8080
    command: /bin/sh -c "while sleep 1000; do :; done"

  eth-node:
    image: eth-node
    build:
      context: ./eth-dev-network
      args:
        - password=password
    expose:
      - 8545
    ports:
      - 8545:8545

# blockscout

  db:
    image: postgres:13.6
    restart: always
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 7432:5432

  blockscout:
    depends_on:
      - db
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    restart: always
    links:
      - db:database
    command: 'mix do ecto.create, ecto.migrate, phx.server'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./common-blockscout.env
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'geth'
        BLOCK_TRANSFORMER: 'clique'
        ETHEREUM_JSONRPC_HTTP_URL: http://host.docker.internal:8545/
        DATABASE_URL: postgresql://postgres:@host.docker.internal:7432/blockscout?ssl=false
        ECTO_USE_SSL: 'false'
    ports:
      - 4000:4000

volumes:
  workspace:
